import {PGlite} from '@electric-sql/pglite';
import {vector} from '@electric-sql/pglite-pgvector';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite({extensions:{vector}});
try {
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
alter default privileges in schema public grant execute on functions to anon,authenticated;
create schema auth; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to authenticated,anon,service_role; grant execute on function auth.uid() to authenticated;`);
for(const file of (await readdir('supabase/migrations')).sort())await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',chat='33333333-3333-4333-8333-333333333333';
await db.query('insert into auth.users(id) values($1),($2)',[a,b]);
await db.exec(`set role authenticated; set request.jwt.claim.sub='${a}'`);
assert.equal((await db.query('select * from profiles')).rows.length,1);
await db.query('insert into chats(id,user_id) values($1,$2)',[chat,a]);
await db.query("select save_research_turn($1,'Mars','Evidence [1]','[]','[]',true,false,'[\"Caveat\"]')",[chat]);
assert.equal((await db.query('select warnings from messages')).rows[0].warnings[0],'Caveat');
await assert.rejects(db.query('insert into chats(user_id) values($1)',[b]));
await assert.rejects(db.query('update chats set user_id=$1',[b]));
for(let i=0;i<30;i++)assert.equal((await db.query('select consume_research_quota() as ok')).rows[0].ok,true);
assert.equal((await db.query('select consume_research_quota() as ok')).rows[0].ok,false);
await assert.rejects(db.query('delete from research_usage'));
await db.exec(`set request.jwt.claim.sub='${b}'`);
assert.equal((await db.query('select * from chats')).rows.length,0);
assert.equal((await db.query('select * from messages')).rows.length,0);
await assert.rejects(db.query("select save_research_turn($1,'No','No','[]','[]',false,false)",[chat]));
await assert.rejects(db.query("insert into messages(chat_id,user_id,question,answer) values($1,$2,'No','No')",[chat,b]));
assert.equal((await db.query('select consume_research_quota() as ok')).rows[0].ok,true);
await db.exec('reset role');
await db.query("insert into paper_chunks(id,doc_id,title,origin,content) values('p','doc','Mars','arxiv','Mars has polar ice')");
await db.exec('set role authenticated');
assert.equal((await db.query("select * from match_papers(null,'Mars',5)")).rows.length,1);
assert.equal((await db.query('select * from paper_library')).rows.length,1);
await assert.rejects(db.query('delete from paper_chunks'));
await db.exec('set role anon');
await assert.rejects(db.query('select * from profiles'));
await assert.rejects(db.query('select * from paper_library'));
await assert.rejects(db.query('select consume_research_quota()'));
await db.exec('reset role');
await db.query('delete from auth.users where id=$1',[a]);
assert.equal((await db.query('select * from messages')).rows.length,0);
assert.equal((await db.query('select * from chats')).rows.length,0);
console.log('PASS: both migrations, profile trigger, two-user RLS, forged ownership, quota, paper search, anonymous denial, cascade deletion');
} finally {await db.close();}
