"""Collect existing full-text chunks and fresh, explicitly labelled abstracts.

Uses only Python's standard library. Writes JSONL for import_supabase_papers.py.
No vector database is created or committed. Bibliographic metadata is fetched
from arXiv/NTRS, never guessed from filenames or generated by a language model.
"""
import argparse
import hashlib
import json
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from import_supabase_papers import rows, chunks

ATOM = {'a': 'http://www.w3.org/2005/Atom'}
CATEGORIES = ['astro-ph.SR', 'astro-ph.CO', 'astro-ph.EP', 'astro-ph.HE']

def get(url):
    request = urllib.request.Request(url, headers={'User-Agent':'SpaceMind/0.5 (astronomy research library)'})
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                return response.read()
        except Exception:
            if attempt == 2: raise
            time.sleep(3 * (attempt + 1))

def arxiv(params):
    xml = ET.fromstring(get('https://export.arxiv.org/api/query?' + urllib.parse.urlencode(params)))
    papers=[]
    for entry in xml.findall('a:entry', ATOM):
        identifier=entry.findtext('a:id','',ATOM).split('/abs/')[-1]
        if not identifier or identifier.startswith('http'): continue
        title=' '.join(entry.findtext('a:title','',ATOM).split())
        if title.lower()=='error': raise RuntimeError('arXiv query failed')
        published=entry.findtext('a:published','',ATOM)
        papers.append({'doc_id':'arxiv:'+identifier,'arxiv_id':identifier,'title':title,
            'authors':[a.findtext('a:name','',ATOM) for a in entry.findall('a:author',ATOM)],
            'year':int(published[:4]) if published[:4].isdigit() else None,
            'categories':[c.attrib['term'] for c in entry.findall('a:category',ATOM)],
            'url':'https://arxiv.org/abs/'+identifier,'origin':'arxiv_abstract',
            'abstract':' '.join(entry.findtext('a:summary','',ATOM).split())})
    time.sleep(3) # arXiv API guidance
    return papers

def ntrs_metadata(citation):
    published=citation.get('publicationDate','')
    authors=[]
    for author in citation.get('authorAffiliations',[]):
        value=author.get('meta',{}).get('author',{}).get('name')
        if not value: value=author.get('name')
        if value: authors.append(value)
    return {'doc_id':'ntrs:'+str(citation['id']),'title':citation.get('title','NASA report'),
        'authors':authors,'year':int(published[:4]) if published[:4].isdigit() else None,
        'arxiv_id':None,'categories':['NASA NTRS'],'origin':'ntrs_abstract',
        'url':'https://ntrs.nasa.gov/citations/'+str(citation['id']),
        'abstract':citation.get('abstract','')}

def collect(database, count, output):
    existing=list({r['id']:r for r in rows(database)}.values()) if database.exists() else []
    metadata={}; added=[]; errors=[]
    def add(papers):
        for paper in papers:
            metadata[paper['doc_id']]=paper
            for text in chunks(paper['abstract']):
                item={k:v for k,v in paper.items() if k!='abstract'}
                item['content']=text
                item['id']=hashlib.sha256((item['origin']+'\0'+item['doc_id']+'\0'+text).encode()).hexdigest()
                added.append(item)
    ids=[i.split(':',1)[1] for i in sorted(set(r['doc_id'] for r in existing)) if i.startswith('arxiv:')]
    if ids:
        try: add(arxiv({'id_list':','.join(ids),'max_results':len(ids)}))
        except Exception as error: errors.append('Existing arXiv metadata: '+str(error))
    for category in CATEGORIES:
        try:
            papers=arxiv({'search_query':'cat:'+category,'max_results':count,'sortBy':'submittedDate','sortOrder':'descending'})
            if not papers: raise RuntimeError('No papers returned')
            add(papers); print(category,len(papers),flush=True)
        except Exception as error: errors.append(category+': '+str(error))
    try:
        payload=json.loads(get('https://ntrs.nasa.gov/api/citations/search?'+urllib.parse.urlencode({'q':'exoplanets astronomy','page.size':count})))
        papers=[ntrs_metadata(r.get('citation',r)) for r in payload.get('results',[])]
        if not papers: raise RuntimeError('No NASA reports returned')
        add(papers);print('NASA NTRS',len(papers),flush=True)
    except Exception as error: errors.append('NASA NTRS: '+str(error))
    for identifier in sorted(set(r['doc_id'] for r in existing)):
        if identifier.startswith('ntrs:') and identifier not in metadata:
            try:
                citation=json.loads(get('https://ntrs.nasa.gov/api/citations/'+identifier.split(':',1)[1]))
                metadata[identifier]=ntrs_metadata(citation)
            except Exception as error: errors.append(identifier+': '+str(error))
    for item in existing:
        meta=metadata.get(item['doc_id'],{})
        for key in ['title','authors','year','arxiv_id','categories']:
            if key in meta: item[key]=meta[key]
    combined={item['id']:item for item in existing+added}
    output.parent.mkdir(parents=True,exist_ok=True)
    with output.open('w') as stream:
        for item in combined.values(): stream.write(json.dumps(item,ensure_ascii=False)+'\n')
    manifest={'chunks':len(combined),'papers':len(set(i['doc_id'] for i in combined.values())),
        'existing_fulltext_chunks':len(existing),'abstract_chunks':len(added),'errors':errors}
    output.with_suffix('.manifest.json').write_text(json.dumps(manifest,indent=2))
    print(json.dumps(manifest),flush=True)
    if errors: raise SystemExit('Corpus was saved, but some sources failed; inspect the manifest before importing.')

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--database',type=Path,default=Path('data/chroma_db/chroma.sqlite3'))
    p.add_argument('--per-source',type=int,default=15)
    p.add_argument('--output',type=Path,default=Path('data/processed/hosted-corpus.jsonl'))
    a=p.parse_args();collect(a.database,a.per_source,a.output)
